
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 12 11:42:13 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATER_OR_EQUAL = 45;
  public static final int INCREMENT = 22;
  public static final int CONST = 5;
  public static final int CHAR = 12;
  public static final int PERIOD = 19;
  public static final int NOT_EQUAL = 42;
  public static final int GREATER = 43;
  public static final int CONTINUE = 17;
  public static final int INT = 10;
  public static final int LESS = 44;
  public static final int MINUS = 34;
  public static final int DECREMENT = 23;
  public static final int SEMICOLON = 6;
  public static final int AND = 32;
  public static final int LESS_OR_EQUAL = 46;
  public static final int OR = 31;
  public static final int BOOL = 11;
  public static final int COMMA = 7;
  public static final int LEFT_BRACE = 3;
  public static final int DIV = 39;
  public static final int RIGHT_PARENTHESIS = 14;
  public static final int QUESTION_MARK = 33;
  public static final int PLUS = 37;
  public static final int ASSIGN = 8;
  public static final int IF = 24;
  public static final int EOF = 0;
  public static final int RETURN = 28;
  public static final int EQUAL = 41;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 38;
  public static final int RIGHT_BRACE = 4;
  public static final int MOD = 40;
  public static final int BREAK = 16;
  public static final int VOID = 15;
  public static final int LEFT_SQUARE = 20;
  public static final int COLON = 18;
  public static final int ELSE = 25;
  public static final int ENUM = 36;
  public static final int READ = 29;
  public static final int WHILE = 27;
  public static final int RIGHT_SQUARE = 21;
  public static final int PRINT = 30;
  public static final int LEFT_PARENTHESIS = 13;
  public static final int DO = 26;
  public static final int IDENTIFIER = 9;
}

